import type { Metadata } from "next";
// import {Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import {ClerkProvider} from "@clerk/nextjs"
import CreateEventDrawer from "@/components/CreateEventDrawer"
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
       <body >
          <Header />
          <main className=" bg-gradient-to-b from-blue-50 to-white">
            {children}
          </main>
          <footer className="bg-gray-800 ">
            <div className="container mx-auto px-4 text-center text-gray-600">
              <p>All Rights Reserved @OMR_INDIA</p>
            </div>
          </footer>
          <Suspense>
        <CreateEventDrawer />
      </Suspense>
        </body>
    </html>
    </ClerkProvider>
  );
}
